title: Just AI Corner
description: A personal blog for AI using the Just the Docs theme!
theme: just-the-docs

url: https://dinhnguyenngoc.github.io/just-ai

aux_links:
  Template Repository: https://github.com/dinhnguyenngoc/just-ai
