title: Just News Corner
description: A personal blog for AI, and Technology!
theme: just-the-docs

url: https://dinhnguyenngoc.github.io/news-feed

aux_links:
  #Template Repository: https://github.com/dinhnguyenngoc/news-feed  
  macOS Apps List: https://github.com/dinhnguyenngoc/learning-notes/blob/b99037d3acce9ec4c4119947af03b3ed6bd1f3cd/macOS-App-List/macOS-App-List.pdf
  ChatGPT Use Cases: https://github.com/dinhnguyenngoc/learning-notes/blob/main/ChatGPT-Use-Cases/ChatGPT%20-%2023%20Use%20Cases.pdf
  Đỉnh Nguyễn's GitHub: https://github.com/dinhnguyenngoc